print("POST /directory/youpi.bla HTTP/1.1\r\n", end="", flush=True)
print("Host: localhost:4343\r\n", end="", flush=True)
print("User-Agent: Go-http-client/1.1\r\n", end="", flush=True)
print("Transfer-Encoding: chunked\r\n", end="", flush=True)
print("Content-Type: test/file\r\n", end="", flush=True)
print("Accept-Encoding: gzip\r\n", end="", flush=True)
print("\r\n", end="", flush=True)
print("80\r\n", end="", flush=True)
print("pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp\r\n", end="", flush=True)
print("0\r\n", end="", flush=True)
print("\r\n", end="", flush=True)
